# Generated by Django 3.2.9 on 2021-11-14 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('column_separator', models.CharField(choices=[(',', 'Comma(,)'), (';', 'Semicolon(;)'), ('|', 'Pipe(|)')], default=',', max_length=30)),
                ('string_character', models.CharField(choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')")], default='"', max_length=30)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Ready', 'Ready')], default='Processing', max_length=20)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_csv_app.schema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('Full name', 'Full name'), ('Email', 'Email'), ('Phone number', 'Phone number'), ('Job', 'Job'), ('Integer', 'Integer'), ('Company', 'Company')], default='Integer', max_length=20)),
                ('From', models.IntegerField(blank=True, null=True)),
                ('To', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='fake_csv_app.schema')),
            ],
        ),
    ]
